caligraph:
  namespace: 'http://data.informatik.uni-mannheim.de/caligraph#'
category:
  root_category: 'http://dbpedia.org/resource/Category:Main_topic_classifications'
  dbp_types:
    exclude_untyped_resources: False
    prefer_resource_types: True
    apply_type_depth_smoothing: True
    apply_impure_type_filtering: True
    type_purity_threshold: 0.95
    resource_type_ratio: 0.5
    child_type_ratio: 0.5
cat2ax:
  use_materialized_category_graph: False
  pattern_confidence: 0.05


logging:
  level: 'DEBUG'
  to_file: True
  filename: 'listparse-v2'

mailer:
  sender: 'errors.nheist@gmail.com'
  password: 'Asdf1234!'
  receiver: 'nico.heist@gmail.com'
  subject: 'CaLiGraph | '
  enable:
    success: True
    error: True

files:
  dbpedia:
    pages:
      filename: 'pages_articles_en.xml.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/pages_articles_en.xml.bz2'
    taxonomy:
      filename: 'dbpedia_2016-10.nt'
      url: 'http://downloads.dbpedia.org/2016-10/dbpedia_2016-10.nt'
    labels:
      filename: 'labels_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/labels_en.ttl.bz2'
    long_abstracts:
      filename: 'long_abstracts_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/long_abstracts_en.ttl.bz2'
    categories:
      filename: 'skos_categories_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/skos_categories_en.ttl.bz2'
    topical_concepts:
      filename: 'topical_concepts_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/topical_concepts_en.ttl.bz2'
    category_redirects:
      filename: 'category_redirects_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/redirects_en.ttl.bz2'
    article_categories:
      filename: 'article_categories_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/article_categories_en.ttl.bz2'
    instance_types:
      filename: 'instance_types_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/instance_types_en.ttl.bz2'
    transitive_instance_types:
      filename: 'instance_types_transitive_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/instance_types_transitive_en.ttl.bz2'
    instance_types_sdtyped:
      filename: 'instance_types_sdtyped_dbo_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/instance_types_sdtyped_dbo_en.ttl.bz2'
    instance_types_lhd:
      filename: 'instance_types_lhd_dbo_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core/instance_types_lhd_dbo_en.ttl.bz2'
    mappingbased_literals:
      filename: 'mappingbased_literals_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/mappingbased_literals_en.ttl.bz2'
    mappingbased_objects:
      filename: 'mappingbased_objects_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/mappingbased_objects_en.ttl.bz2'
    interlanguage_links:
      filename: 'interlanguage_links_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/interlanguage_links_en.ttl.bz2'
    anchor_texts:
      filename: 'anchor_text_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/anchor_text_en.ttl.bz2'
    redirects:
      filename: 'redirects_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/redirects_en.ttl.bz2'
    disambiguations:
      filename: 'disambiguations_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/disambiguations_en.ttl.bz2'
    maintenance_categories:
      filename: 'maintenance_categories.ttl.bz2'
    type_surface_forms:
      filename: 'type_surface_forms_total.p.bz2'
  wikidata:
    resource_properties:
      filename: 'wikidata_resource_properties.nt.bz2'
      url: ~
  webisalod:
    instances:
      filename: 'webisalod-instances.nq.gz'
      url: 'http://data.dws.informatik.uni-mannheim.de/webisa/webisalod-instances.nq.gz'
  evaluation:
    catgraph_dbptypes:
      filename: 'catgraph-dbptype_labels.csv'
    cataxioms:
      filename: 'cataxioms_labels.csv'

results:
  catgraph:
    dbp_type_sample: 'dbp-type-sample.csv'
  cat2ax:
    relation_axioms: 'cat2ax_relation-axioms.csv'
    type_axioms: 'cat2ax_type-axioms.csv'
    relation_assertions: 'cat2ax_relation-assertions.csv'
    type_assertions: 'cat2ax_type-assertions.csv'

cache:
  # version 2: added resource types from sdtyped + lhd
  catgraph_conceptual:
    filename: 'catgraph-conceptual'
    version: 1
  catgraph_cyclefree:
    filename: 'catgraph-cyclefree'
    version: 1
  catgraph_dbp_typed:
    filename: 'catgraph-dbp-typed'
    version: 1
  catgraph_taxonomic:
    filename: 'catgraph-taxonomic'
    version: 1
  catgraph_wikitaxonomy:
    filename: 'catgraph-wikitaxonomy'
    version: 1
  categories_singularized:
    filename: 'categories-singularized'
    version: 1
  spacy_docs:
    filename: 'spacy-docs'
    version: 2  # version 2 incl. listpages
  dbpedia_resource_type_cooccurrence_matrix:
    filename: 'dbpedia-resource-type-cooccurrence-matrix'
    version: 1
  dbpedia_resource_type_frequency:
    filename: 'dbpedia-resource-type-frequency'
    version: 1
  dbpedia_resource_type_mapping:
    filename: 'dbpedia-resource-type-mapping'
    version: 1
  dbpedia_resource_labels:
    filename: 'dbpedia-resource-labels'
    version: 1
  dbpedia_resource_abstracts:
    filename: 'dbpedia-resource-abstracts'
    version: 1
  dbpedia_resource_surface_forms:
    filename: 'dbpedia-resource-surface-forms'
    version: 1
  dbpedia_resource_inverse_surface_forms:
    filename: 'dbpedia-resource-inverse-surface-forms'
    version: 1
  dbpedia_resource_categories:
    filename: 'dbpedia-resource-categories'
    version: 1
  dbpedia_resource_properties:
    filename: 'dbpedia-resource-properties'
    version: 1
  dbpedia_inverse_resource_properties:
    filename: 'dbpedia-inverse-resource-properties'
    version: 1
  dbpedia_resource_interlanguage_links:
    filename: 'dbpedia-resource-interlanguage-links'
    version: 1
  dbpedia_resource_redirects:
    filename: 'dbpedia-resource-redirects'
    version: 1
  dbpedia_resource_disambiguations:
    filename: 'dbpedia-resource-disambiguations'
    version: 1
  dbpedia_functional_predicates:
    filename: 'dbpedia-functional-predicates'
    version: 2  # version 1: strict; version 2: 5% tolerance
  dbpedia_categories:
    filename: 'dbpedia-categories'
    version: 1
  dbpedia_category_resources:
    filename: 'dbpedia-category-resources'
    version: 1
  dbpedia_category_children:
    filename: 'dbpedia-category-children'
    version: 1
  dbpedia_category_statistics:
    filename: 'dbpedia-category-statistics'
    version: 1
  dbpedia_materialized_category_statistics:
    filename: 'dbpedia-materialized-category-statistics'
    version: 1
  dbpedia_category_sets:
    filename: 'dbpedia-category-sets'
    version: 1
  dbpedia_categories_conceptual:
    filename: 'dbpedia-category-conceptual'
    version: 1
  dbpedia_property_frequency_distribution:
    filename: 'dbpedia-property-frequency-distribution'
    version: 1
  dbpedia_inverse_property_frequency_distribution:
    filename: 'dbpedia-inverse-property-frequency-distribution'
    version: 1
  dbpedia_heuristic_domains:
    filename: 'dbpedia-heuristic-domains'
    version: 1
  dbpedia_heuristic_ranges:
    filename: 'dbpedia-heuristic-ranges'
    version: 1
  dbpedia_heuristic_disjoint_types:
    filename: 'dbpedia-heuristic-disjoint-types'
    version: 1
  dbpedia_listpages:
    filename: 'dbpedia-listpages'
    version: 1
  dbpedia_listpage_equivalents:
    filename: 'dbpedia-listpage-equivalents'
    version: 1
  dbpedia_listpage_children:
    filename: 'dbpedia-listpage-children'
    version: 1
  dbpedia_listpage_markup:
    filename: 'dbpedia-listpage-markup'
    version: 1
  dbpedia_listpage_parsed:
    filename: 'dbpedia-listpage-parsed'
    version: 2  # v1: basic; v2: with entity indices
  wikidata_dbpedia_resource_mapping:
    filename: 'wikidata-dbpedia-resource-mapping'
    version: 1
    compress: True
  wikidata_resource_properties:
    filename: 'wikidata-resource-properties'
    version: 1
    compress: True
  wikitaxonomy_edges:
    filename: 'wikitaxonomy-edges'
    version: 1
  wikitaxonomy_hypernyms:
    filename: 'wikitaxonomy-hypernyms'
    version: 1  # version 1 -> thresholds 10 / 100 / .4
  cat2ax_axioms:
    filename: 'cat2ax-axioms'
    version: 1