caligraph:
  namespace: 'http://data.informatik.uni-mannheim.de/caligraph#'
  category:
    root_category: 'http://dbpedia.org/resource/Category:Main_topic_classifications'
    dbp_types:
      exclude_untyped_resources: False
      apply_type_depth_smoothing: True
      resource_type_ratio: 0.3
      child_type_ratio: 0.4


logging:
  level: 'DEBUG'
  to_file: False
  filename: 'log_test'

files:
  dbpedia:
    pages: 'pages_articles_en.xml.bz2'
    taxonomy: 'dbpedia_2016-10.nt'
    categories: 'skos_categories_en.ttl.bz2'
    topical_concepts: 'topical_concepts_en.ttl.bz2'
    category_redirects: 'category_redirects_en.ttl.bz2'
    article_categories: 'article_categories_en.ttl.bz2'
    maintenance_categories: 'maintenance_categories.ttl.bz2'
    instance_types: 'instance_types_en.ttl.bz2'
    transitive_instance_types: 'instance_types_transitive_en.ttl.bz2'
    mappingbased_literals: 'mappingbased_literals_en.ttl.bz2'
    mappingbased_objects: 'mappingbased_objects_en.ttl.bz2'
    interlanguage_links: 'interlanguage_links_en.ttl.bz2'
  wikidata:
    resource_properties: 'wikidata_resource_properties.nt.bz2'

cache:
  catgraph_conceptual:
    filename: 'catgraph-conceptual'
    version: 1
  catgraph_cyclefree:
    filename: 'catgraph-cyclefree'
    version: 1
  catgraph_dbp_typed:
    filename: 'catgraph-dbp-typed'
    version: 1
  categories_conceptual:
    filename: 'categories-conceptual'
    version: 1
  categories_singularized:
    filename: 'categories-singularized'
    version: 1
  spacy_docs:
    filename: 'spacy-docs'
    version: 1
  dbpedia_resource_type_frequency:
    filename: 'dbpedia-resource-type-frequency'
    version: 1
  dbpedia_resource_type_mapping:
    filename: 'dbpedia-resource-type-mapping'
    version: 1
  dbpedia_resource_categories:
    filename: 'dbpedia-resource-categories'
    version: 1
  dbpedia_resource_properties:
    filename: 'dbpedia-resource-properties'
    version: 1
  dbpedia_resource_interlanguage_links:
    filename: 'dbpedia-resource-interlanguage-links'
    version: 1
  dbpedia_categories:
    filename: 'dbpedia-categories'
    version: 1
  dbpedia_category_resources:
    filename: 'dbpedia-category-resources'
    version: 1
  dbpedia_category_parents:
    filename: 'dbpedia-category-parents'
    version: 1
  dbpedia_category_children:
    filename: 'dbpedia-category-children'
    version: 1
  dbpedia_property_frequency_distribution:
    filename: 'dbpedia-property-frequency-distribution'
    version: 1
  wikidata_dbpedia_resource_mapping:
    filename: 'wikidata-dbpedia-resource-mapping'
    version: 1