# -- SYSTEM CONFIGURATION --
max_cpus: 16

# -- CALIGRAPH CONFIGURATION --
caligraph:
  version: '1.1'
  creation_date: '2020-06-24'
  namespace:
    base: 'http://caligraph.org/'
    ontology: 'http://caligraph.org/ontology/'
    resource: 'http://caligraph.org/resource/'
category:
  root_category: 'http://dbpedia.org/resource/Category:Main_topic_classifications'
page:
  extraction:
    use_negative_evidence_assumption: True
    extract_unlinked_entities: True
    use_robust_extraction: False
cat2ax:
  pattern_confidence: 0.05

# -- LOGGING CONFIGURATION --
logging:
  level: 'DEBUG'
  to_file: True
  filename: 'caligraph_v1_1'

# -- ERROR-MAILER CONFIGURATION --
# -> add information about your mail accounts here and enable the `success` or `error` switches
#    if you want to receive information about success or failure of the extraction by mail. <-
mailer:
  sender: errors.nheist@gmail.com
  password: Asdf1234!
  receiver: nico@informatik.uni-mannheim.de
  subject: 'CaLiGraph | '
  enable:
    success: True
    error: True

# -- SOURCE FILE CONFIGURATION --
files:
  dbpedia:
    pages:
      filename: 'pages_articles_en.xml.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/pages_articles_en.xml.bz2'
    taxonomy_owl:
      filename: 'dbpedia_2016-10.owl'
      url: 'http://downloads.dbpedia.org/2016-10/dbpedia_2016-10.owl'
    taxonomy:
      filename: 'dbpedia_2016-10.nt'
      url: 'http://downloads.dbpedia.org/2016-10/dbpedia_2016-10.nt'
    labels:
      filename: 'labels_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/labels_en.ttl.bz2'
    long_abstracts:
      filename: 'long_abstracts_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/long_abstracts_en.ttl.bz2'
    categories:
      filename: 'skos_categories_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/skos_categories_en.ttl.bz2'
    topical_concepts:
      filename: 'topical_concepts_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/topical_concepts_en.ttl.bz2'
    article_categories:
      filename: 'article_categories_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/article_categories_en.ttl.bz2'
    instance_types:
      filename: 'instance_types_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/instance_types_en.ttl.bz2'
    transitive_instance_types:
      filename: 'instance_types_transitive_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/instance_types_transitive_en.ttl.bz2'
    instance_types_sdtyped:
      filename: 'instance_types_sdtyped_dbo_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/instance_types_sdtyped_dbo_en.ttl.bz2'
    instance_types_lhd:
      filename: 'instance_types_lhd_dbo_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core/instance_types_lhd_dbo_en.ttl.bz2'
    mappingbased_literals:
      filename: 'mappingbased_literals_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/mappingbased_literals_en.ttl.bz2'
    mappingbased_objects:
      filename: 'mappingbased_objects_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/mappingbased_objects_en.ttl.bz2'
    anchor_texts:
      filename: 'anchor_text_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/anchor_text_en.ttl.bz2'
    redirects:
      filename: 'redirects_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/redirects_en.ttl.bz2'
    disambiguations:
      filename: 'disambiguations_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/disambiguations_en.ttl.bz2'
    nif_context:
      filename: 'nif_context_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/nif_context_en.ttl.bz2'
    maintenance_categories:
      filename: 'maintenance_categories.ttl.bz2'
    wikipedia_hypernyms:
      filename: 'wiki_hypernyms_lemmas.p.bz2'
      url: 'http://data.dws.informatik.uni-mannheim.de/CaLiGraph/data/wiki_hypernyms_lemmas.p.bz2'
    webisalod_hypernyms:
      filename: 'webisalod_hypernyms.p.bz2'
      url: 'http://data.dws.informatik.uni-mannheim.de/CaLiGraph/data/webisalod_hypernyms.p.bz2'
  listpages:
    goldstandard_named-entity-tagging:
      filename: 'goldstandard_list-page-named-entity-tagging.json'
      url: 'http://data.dws.informatik.uni-mannheim.de/CaLiGraph/data/goldstandard_list-page-named-entity-tagging.json'

# -- RESULT FILE CONFIGURATION --
results:
  caligraph:
    metadata: 'caligraph-metadata.nt.bz2'  # void description
    ontology: 'caligraph-ontology.nt.bz2'  # class hierarchy, labels
    ontology_dbpedia-mapping: 'caligraph-ontology_dbpedia-mapping.nt.bz2'  # equivalent classes and equivalent properties in DBpedia
    ontology_provenance: 'caligraph-ontology_provenance.nt.bz2'  # provenance information for classes
    instances_types: 'caligraph-instances_types.nt.bz2'  # instance types
    instances_transitive-types: 'caligraph-instances_transitive-types.nt.bz2'  # (additional) materialized instance types
    instances_labels: 'caligraph-instances_labels.nt.bz2'  # instance labels
    instances_relations: 'caligraph-instances_relations.nt.bz2'  # materialized relations from restrictions
    instances_dbpedia-mapping: 'caligraph-instances_dbpedia-mapping.nt.bz2'  # sameAs links to DBpedia
    instances_provenance: 'caligraph-instances_provenance.nt.bz2'  # provenance information for instances

    dbpedia_instances: 'dbpedia_caligraph-instances.nt.bz2'  # new dbpedia instances found through CaLiGraph
    dbpedia_instance-types: 'dbpedia_caligraph-types.nt.bz2'  # new dbpedia types found through CaLiGraph
    dbpedia_instance-caligraph-types: 'dbpedia_caligraph-clg-types.nt.bz2'  # all CaLiGraph types that can be assigned to DBpedia resources
    dbpedia_instance-transitive-caligraph-types: 'dbpedia_caligraph-transitive-clg-types.nt.bz2'  # all transitive CaLiGraph types that can be assigned to DBpedia resources
    dbpedia_instance-relations: 'dbpedia_caligraph-relations.nt.bz2'  #  new dbpedia relations found through CaLiGraph

# -- CACHE FILE CONFIGURATION --
cache:
  catgraph_conceptual:
    filename: 'catgraph-conceptual'
    version: 1
  catgraph_wikitaxonomy:
    filename: 'catgraph-wikitaxonomy'
    version: 1
  catgraph_cyclefree:
    filename: 'catgraph-cyclefree'
    version: 1
  catgraph_merged:
    filename: 'catgraph-merged'
    version: 2
  listgraph_base:
    filename: 'listgraph-base'
    version: 1
  listgraph_wikitaxonomy:
    filename: 'listgraph-wikitaxonomy'
    version: 1
  listgraph_cyclefree:
    filename: 'listgraph-cyclefree'
    version: 1
  listgraph_merged:
    filename: 'listgraph-merged'
    version: 2
  caligraph_base:
    filename: 'caligraph-base'
    version: 2
  caligraph_merged_ontology:
    filename: 'caligraph-merged-ontology'
    version: 2
  caligraph_filtered:
    filename: 'caligraph-filtered'
    version: 2  # SIMPLE: 2 // ROBUST: 3
  caligraph_axiomatized:
    filename: 'caligraph-axiomatized'
    version: 2  # SIMPLE: 2 // ROBUST: 3
  spacy_docs:
    filename: 'spacy-docs'
    version: 1
  dbpedia_page_markup:
    filename: 'dbpedia-page-markup'
    version: 1
    compress: True
  dbpedia_page_parsed:
    filename: 'dbpedia-page-parsed'
    version: 2
  dbpedia_resources:
    filename: 'dbpedia-resources'
    version: 1
  dbpedia_resource_type_frequency:
    filename: 'dbpedia-resource-type-frequency'
    version: 1
  dbpedia_resource_type_mapping:
    filename: 'dbpedia-resource-type-mapping'
    version: 1
  dbpedia_resource_labels:
    filename: 'dbpedia-resource-labels'
    version: 1
  dbpedia_resource_abstracts:
    filename: 'dbpedia-resource-abstracts'
    version: 1
  dbpedia_resource_lexicalisations:
    filename: 'dbpedia-resource-lexicalisations'
    version: 1
  dbpedia_resource_inverse_lexicalisations:
    filename: 'dbpedia-resource-inverse-lexicalisations'
    version: 1
  dbpedia_resource_categories:
    filename: 'dbpedia-resource-categories'
    version: 1
  dbpedia_resource_properties:
    filename: 'dbpedia-resource-properties'
    version: 1
  dbpedia_inverse_resource_properties:
    filename: 'dbpedia-inverse-resource-properties'
    version: 1
  dbpedia_resource_redirects:
    filename: 'dbpedia-resource-redirects'
    version: 1
  dbpedia_resource_disambiguations:
    filename: 'dbpedia-resource-disambiguations'
    version: 1
  dbpedia_type_lexicalisations:
    filename: 'dbpedia-type-lexicalisations'
    version: 1
    compress: True
  dbpedia_functional_predicates:
    filename: 'dbpedia-functional-predicates'
    version: 1
  dbpedia_categories:
    filename: 'dbpedia-categories'
    version: 1
  dbpedia_category_resources:
    filename: 'dbpedia-category-resources'
    version: 1
  dbpedia_category_children:
    filename: 'dbpedia-category-children'
    version: 1
  dbpedia_category_statistics:
    filename: 'dbpedia-category-statistics'
    version: 1
  dbpedia_category_sets:
    filename: 'dbpedia-category-sets'
    version: 1
  dbpedia_categories_conceptual:
    filename: 'dbpedia-category-conceptual'
    version: 1
  dbpedia_heuristic_domains:
    filename: 'dbpedia-heuristic-domains'
    version: 1
  dbpedia_heuristic_ranges:
    filename: 'dbpedia-heuristic-ranges'
    version: 1
  dbpedia_heuristic_disjoint_types:
    filename: 'dbpedia-heuristic-disjoint-types'
    version: 1
  dbpedia_listpages:
    filename: 'dbpedia-listpages'
    version: 1
  dbpedia_list_equivalents:
    filename: 'dbpedia-list-equivalents'
    version: 2
  dbpedia_list_parents:
    filename: 'dbpedia-list-parents'
    version: 2
  dbpedia_listpage_parsed:
    filename: 'dbpedia-listpage-parsed'
    version: 2
  dbpedia_listpage_enum_features:
    filename: 'dbpedia-listpage-enum-features'
    version: 2  # SIMPLE: 2 // ROBUST: 3
    store_as_csv: True
  dbpedia_listpage_table_features:
    filename: 'dbpedia-listpage-table-features'
    version: 2  # SIMPLE: 2 // ROBUST: 3
    store_as_csv: True
  dbpedia_listpage_entities:
    filename: 'dbpedia-listpage-entities'
    version: 2  # SIMPLE: 2 // ROBUST: 3
  wikitaxonomy_hypernyms:
    filename: 'wikitaxonomy-hypernyms'
    version: 1
  cat2ax_axioms:
    filename: 'cat2ax-axioms'
    version: 1
  spacy_listpage_ne-tagging_GS:
    filename: 'spacy_listpage_ne-tagging_GS'
    version: 1
    store_as_folder: True
  spacy_listpage_ne-tagging_GS-WLE:
    filename: 'spacy_listpage_ne-tagging_GS-WLE'
    version: 1
    store_as_folder: True
