caligraph:
  namespace: 'http://data.informatik.uni-mannheim.de/caligraph#'
  category:
    root_category: 'http://dbpedia.org/resource/Category:Main_topic_classifications'
    dbp_types:
      exclude_untyped_resources: False
      apply_type_depth_smoothing: True
      apply_impure_type_filtering: True
      type_purity_threshold: 0.95
      resource_type_ratio: 0.5
      child_type_ratio: 0.5


logging:
  level: 'INFO'
  to_file: True
  # filename: 'heuristics_disjoint-domains'
  filename: 'relations-v8_param-optimization'

mailer:
  sender: 'errors.nheist@gmail.com'
  password: 'Asdf1234!'
  receiver: 'nico.heist@gmail.com'
  subject: 'CaLiGraph | '
  enable:
    success: True
    error: True

files:
  dbpedia:
    pages: 'pages_articles_en.xml.bz2'
    taxonomy: 'dbpedia_2016-10.nt'
    labels: 'labels_en.ttl.bz2'
    categories: 'skos_categories_en.ttl.bz2'
    topical_concepts: 'topical_concepts_en.ttl.bz2'
    category_redirects: 'category_redirects_en.ttl.bz2'
    article_categories: 'article_categories_en.ttl.bz2'
    maintenance_categories: 'maintenance_categories.ttl.bz2'
    instance_types: 'instance_types_en.ttl.bz2'
    transitive_instance_types: 'instance_types_transitive_en.ttl.bz2'
    instance_types_sdtyped: 'instance_types_sdtyped_dbo_en.ttl.bz2'
    instance_types_lhd: 'instance_types_lhd_dbo_en.ttl.bz2'
    mappingbased_literals: 'mappingbased_literals_en.ttl.bz2'
    mappingbased_objects: 'mappingbased_objects_en.ttl.bz2'
    interlanguage_links: 'interlanguage_links_en.ttl.bz2'
    anchor_texts: 'anchor_text_en.ttl.bz2'
  wikidata:
    resource_properties: 'wikidata_resource_properties.nt.bz2'

cache:
  # version 2: added resource types from sdtyped + lhd
  catgraph_conceptual:
    filename: 'catgraph-conceptual'
    version: 1
  catgraph_cyclefree:
    filename: 'catgraph-cyclefree'
    version: 1
  catgraph_dbp_typed:
    filename: 'catgraph-dbp-typed'
    version: 2
  categories_conceptual:
    filename: 'categories-conceptual'
    version: 1
  categories_singularized:
    filename: 'categories-singularized'
    version: 1
  spacy_docs:
    filename: 'spacy-docs'
    version: 1
  dbpedia_resource_type_cooccurrence_matrix:
    filename: 'dbpedia-resource-type-cooccurrence-matrix'
    version: 2
  dbpedia_resource_type_frequency:
    filename: 'dbpedia-resource-type-frequency'
    version: 2
  dbpedia_resource_type_mapping:
    filename: 'dbpedia-resource-type-mapping'
    version: 2
  dbpedia_resource_labels:
    filename: 'dbpedia-resource-labels'
    version: 1
  dbpedia_resource_surface_forms:
    filename: 'dbpedia-resource-surface-forms'
    version: 1
  dbpedia_resource_categories:
    filename: 'dbpedia-resource-categories'
    version: 1
  dbpedia_resource_properties:
    filename: 'dbpedia-resource-properties'
    version: 1
  dbpedia_inverse_resource_properties:
    filename: 'dbpedia-inverse-resource-properties'
    version: 1
  dbpedia_resource_interlanguage_links:
    filename: 'dbpedia-resource-interlanguage-links'
    version: 1
  dbpedia_functional_predicates:
    filename: 'dbpedia-functional-predicates'
    version: 1
  dbpedia_heuristic_domains:
    filename: 'dbpedia-heuristic-domains'
    version: 1
  dbpedia_heuristic_ranges:
    filename: 'dbpedia-heuristic-ranges'
    version: 1
  dbpedia_heuristic_disjoint_types:
    filename: 'dbpedia-heuristic-disjoint-types'
    version: 1
  dbpedia_categories:
    filename: 'dbpedia-categories'
    version: 1
  dbpedia_category_resources:
    filename: 'dbpedia-category-resources'
    version: 1
  dbpedia_category_parents:
    filename: 'dbpedia-category-parents'
    version: 1
  dbpedia_category_children:
    filename: 'dbpedia-category-children'
    version: 1
  dbpedia_property_frequency_distribution:
    filename: 'dbpedia-property-frequency-distribution'
    version: 1
  dbpedia_list_equivalents:
    filename: 'dbpedia-list-equivalents'
    version: 1
  dbpedia_list_children:
    filename: 'dbpedia-list-children'
    version: 1
  wikidata_dbpedia_resource_mapping:
    filename: 'wikidata-dbpedia-resource-mapping'
    version: 1
  wikidata_resource_properties:
    filename: 'wikidata-resource-properties'
    version: 1
  relations_property_counts:
    filename: 'relations-property-counts'
    version: 1
  relations_inverse_property_counts:
    filename: 'relations-inverse-property-counts'
    version: 1
  relations_type_counts:
    filename: 'relations-type-counts'
    version: 1
  relations_surface_property_values:
    filename: 'relations-surface-property-values'
    version: 1