caligraph:
  namespace:
    ontology: 'https://caligraph.org/ontology/'
    resource: 'https://caligraph.org/resource/'
category:
  root_category: 'http://dbpedia.org/resource/Category:Main_topic_classifications'
list:
  extraction:
    use_negative_evidence_assumption: True
cat2ax:
  pattern_confidence: 0.05


logging:
  level: 'DEBUG'
  to_file: True
  filename: 'listpage-feature-extraction'

mailer:
  sender: 'errors.nheist@gmail.com'
  password: 'Asdf1234!'
  receiver: 'nico.heist@gmail.com'
  subject: 'CaLiGraph | '
  enable:
    success: True
    error: True

files:
  dbpedia:
    pages:
      filename: 'pages_articles_en.xml.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/pages_articles_en.xml.bz2'
    taxonomy:
      filename: 'dbpedia_2016-10.nt'
      url: 'http://downloads.dbpedia.org/2016-10/dbpedia_2016-10.nt'
    labels:
      filename: 'labels_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/labels_en.ttl.bz2'
    long_abstracts:
      filename: 'long_abstracts_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/long_abstracts_en.ttl.bz2'
    categories:
      filename: 'skos_categories_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/skos_categories_en.ttl.bz2'
    topical_concepts:
      filename: 'topical_concepts_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/topical_concepts_en.ttl.bz2'
    category_redirects:
      filename: 'category_redirects_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/redirects_en.ttl.bz2'
    article_categories:
      filename: 'article_categories_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/article_categories_en.ttl.bz2'
    instance_types:
      filename: 'instance_types_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/instance_types_en.ttl.bz2'
    transitive_instance_types:
      filename: 'instance_types_transitive_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/instance_types_transitive_en.ttl.bz2'
    instance_types_sdtyped:
      filename: 'instance_types_sdtyped_dbo_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/instance_types_sdtyped_dbo_en.ttl.bz2'
    instance_types_lhd:
      filename: 'instance_types_lhd_dbo_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core/instance_types_lhd_dbo_en.ttl.bz2'
    mappingbased_literals:
      filename: 'mappingbased_literals_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/mappingbased_literals_en.ttl.bz2'
    mappingbased_objects:
      filename: 'mappingbased_objects_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/mappingbased_objects_en.ttl.bz2'
    interlanguage_links:
      filename: 'interlanguage_links_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/interlanguage_links_en.ttl.bz2'
    anchor_texts:
      filename: 'anchor_text_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/anchor_text_en.ttl.bz2'
    redirects:
      filename: 'redirects_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/redirects_en.ttl.bz2'
    disambiguations:
      filename: 'disambiguations_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/disambiguations_en.ttl.bz2'
    nif_context:
      filename: 'nif_context_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/nif_context_en.ttl.bz2'
    maintenance_categories:
      filename: 'maintenance_categories.ttl.bz2'
  wikidata:
    resource_properties:
      filename: 'wikidata_resource_properties.nt.bz2'
      url: ~
  webisalod:
    instances:
      filename: 'webisalod-instances.nq.gz'
      url: 'http://data.dws.informatik.uni-mannheim.de/webisa/webisalod-instances.nq.gz'
  evaluation:
    catgraph_dbptypes:
      filename: 'catgraph-dbptype_labels.csv'

results:
  catgraph:
    dbp_type_sample: 'dbp-type-sample.csv'
  cat2ax:
    relation_axioms: 'cat2ax_relation-axioms.csv'
    type_axioms: 'cat2ax_type-axioms.csv'
    relation_assertions: 'cat2ax_relation-assertions.csv'
    type_assertions: 'cat2ax_type-assertions.csv'

cache:
  # version 2: added resource types from sdtyped + lhd
  catgraph_conceptual:
    filename: 'catgraph-conceptual'
    version: 3  # v2: do not remove unconnected nodes initially ; v3: better synonym matching
  catgraph_wikitaxonomy:
    filename: 'catgraph-wikitaxonomy'
    version: 3  # v2: do not remove unconnected nodes initially ; v3: better synonym matching
  catgraph_cyclefree:
    filename: 'catgraph-cyclefree'
    version: 3  # v2: do not remove unconnected nodes initially ; v3: better synonym matching
  catgraph_merged:
    filename: 'catgraph-merged'
    version: 3  # v2: do not remove unconnected nodes initially ; v3: better synonym matching
  categories_singularized:
    filename: 'categories-singularized'
    version: 1
  listgraph_base:
    filename: 'listgraph-base'
    version: 3  # v2: better synonym matching ; v3: with all listpages
  listgraph_wikitaxonomy:
    filename: 'listgraph-wikitaxonomy'
    version: 3  # v2: better synonym matching ; v3: with all listpages
  listgraph_cyclefree:
    filename: 'listgraph-cyclefree'
    version: 3  # v2: better synonym matching ; v3: with all listpages
  listgraph_merged:
    filename: 'listgraph-merged'
    version: 3  # v2: better synonym matching ; v3: with all listpages
  spacy_docs:
    filename: 'spacy-docs'
    version: 3  # version 2 incl. listpages; version 3 for spacy 2.1
  dbpedia_resources:
    filename: 'dbpedia-resources'
    version: 1
  dbpedia_resource_type_cooccurrence_matrix:
    filename: 'dbpedia-resource-type-cooccurrence-matrix'
    version: 1
  dbpedia_resource_type_frequency:
    filename: 'dbpedia-resource-type-frequency'
    version: 1
  dbpedia_resource_type_mapping:
    filename: 'dbpedia-resource-type-mapping'
    version: 1
  dbpedia_resource_labels:
    filename: 'dbpedia-resource-labels'
    version: 1
  dbpedia_resource_abstracts:
    filename: 'dbpedia-resource-abstracts'
    version: 1
  dbpedia_resource_lexicalisations:
    filename: 'dbpedia-resource-lexicalisations'
    version: 1
  dbpedia_resource_inverse_lexicalisations:
    filename: 'dbpedia-resource-inverse-lexicalisations'
    version: 1
  dbpedia_resource_categories:
    filename: 'dbpedia-resource-categories'
    version: 1
  dbpedia_resource_properties:
    filename: 'dbpedia-resource-properties'
    version: 1
  dbpedia_inverse_resource_properties:
    filename: 'dbpedia-inverse-resource-properties'
    version: 1
  dbpedia_resource_interlanguage_links:
    filename: 'dbpedia-resource-interlanguage-links'
    version: 1
  dbpedia_resource_redirects:
    filename: 'dbpedia-resource-redirects'
    version: 1
  dbpedia_resource_disambiguations:
    filename: 'dbpedia-resource-disambiguations'
    version: 1
  dbpedia_type_lexicalisations:
    filename: 'dbpedia-type-lexicalisations'
    version: 1
    compress: True
  dbpedia_functional_predicates:
    filename: 'dbpedia-functional-predicates'
    version: 2  # version 1: strict; version 2: 5% tolerance
  dbpedia_categories:
    filename: 'dbpedia-categories'
    version: 1
  dbpedia_category_resources:
    filename: 'dbpedia-category-resources'
    version: 1
  dbpedia_category_children:
    filename: 'dbpedia-category-children'
    version: 1
  dbpedia_category_statistics:
    filename: 'dbpedia-category-statistics'
    version: 1
  dbpedia_category_sets:
    filename: 'dbpedia-category-sets'
    version: 2  # new conceptual categorygraph version (v2)
  dbpedia_categories_conceptual:
    filename: 'dbpedia-category-conceptual'
    version: 1
  dbpedia_property_frequency_distribution:
    filename: 'dbpedia-property-frequency-distribution'
    version: 1
  dbpedia_inverse_property_frequency_distribution:
    filename: 'dbpedia-inverse-property-frequency-distribution'
    version: 1
  dbpedia_heuristic_domains:
    filename: 'dbpedia-heuristic-domains'
    version: 1
  dbpedia_heuristic_ranges:
    filename: 'dbpedia-heuristic-ranges'
    version: 1
  dbpedia_heuristic_disjoint_types:
    filename: 'dbpedia-heuristic-disjoint-types'
    version: 1
  dbpedia_listpages:
    filename: 'dbpedia-listpages'
    version: 1
  dbpedia_list_equivalents:
    filename: 'dbpedia-list-equivalents'
    version: 2  # v2: better synonym matching
  dbpedia_list_parents:
    filename: 'dbpedia-list-parents'
    version: 2  # v2: better synonym matching
  dbpedia_listpage_markup:
    filename: 'dbpedia-listpage-markup'
    version: 1
  dbpedia_listpage_parsed:
    filename: 'dbpedia-listpage-parsed'
    version: 2  # v1: basic; v2: with entity indices
  dbpedia_listpage_features:
    filename: 'dbpedia-listpage-features'
    version: 3  # v2: transitive entity labeling; v3: + positive axiom labels
  wikidata_dbpedia_resource_mapping:
    filename: 'wikidata-dbpedia-resource-mapping'
    version: 1
    compress: True
  wikidata_resource_properties:
    filename: 'wikidata-resource-properties'
    version: 1
    compress: True
  wikitaxonomy_hypernyms:
    filename: 'wikitaxonomy-hypernyms'
    version: 2  # version 1 -> thresholds 10 / 100 / .4  // v2: new cat2ax version (v2)
  cat2ax_axioms:
    filename: 'cat2ax-axioms'
    version: 2  # new conceptual categorygraph version (v2)