caligraph:
  namespace: 'http://data.informatik.uni-mannheim.de/caligraph#'
category:
  root_category: 'http://dbpedia.org/resource/Category:Main_topic_classifications'
  axioms:
    use_materialized_category_graph: True
    pos_weight: 14
  dbp_types:
    exclude_untyped_resources: False
    apply_type_depth_smoothing: True
    apply_impure_type_filtering: True
    type_purity_threshold: 0.95
    resource_type_ratio: 0.5
    child_type_ratio: 0.5


logging:
  level: 'DEBUG'
  to_file: True
  filename: 'cataxioms-materialized_v1'

mailer:
  sender: 'errors.nheist@gmail.com'
  password: 'Asdf1234!'
  receiver: 'nico.heist@gmail.com'
  subject: 'CaLiGraph | '
  enable:
    success: True
    error: True

files:
  dbpedia:
    pages:
      filename: 'pages_articles_en.xml.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/pages_articles_en.xml.bz2'
    taxonomy:
      filename: 'dbpedia_2016-10.nt'
      url: 'http://downloads.dbpedia.org/2016-10/dbpedia_2016-10.nt'
    labels:
      filename: 'labels_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/labels_en.ttl.bz2'
    categories:
      filename: 'skos_categories_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/skos_categories_en.ttl.bz2'
    topical_concepts:
      filename: 'topical_concepts_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/topical_concepts_en.ttl.bz2'
    category_redirects:
      filename: 'category_redirects_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/redirects_en.ttl.bz2'
    article_categories:
      filename: 'article_categories_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/article_categories_en.ttl.bz2'
    instance_types:
      filename: 'instance_types_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/instance_types_en.ttl.bz2'
    transitive_instance_types:
      filename: 'instance_types_transitive_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/instance_types_transitive_en.ttl.bz2'
    instance_types_sdtyped:
      filename: 'instance_types_sdtyped_dbo_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/instance_types_sdtyped_dbo_en.ttl.bz2'
    instance_types_lhd:
      filename: 'instance_types_lhd_dbo_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core/instance_types_lhd_dbo_en.ttl.bz2'
    mappingbased_literals:
      filename: 'mappingbased_literals_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/mappingbased_literals_en.ttl.bz2'
    mappingbased_objects:
      filename: 'mappingbased_objects_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/mappingbased_objects_en.ttl.bz2'
    interlanguage_links:
      filename: 'interlanguage_links_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/interlanguage_links_en.ttl.bz2'
    anchor_texts:
      filename: 'anchor_text_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/anchor_text_en.ttl.bz2'
    redirects:
      filename: 'redirects_en.ttl.bz2'
      url: 'http://downloads.dbpedia.org/2016-10/core-i18n/en/redirects_en.ttl.bz2'
    maintenance_categories:
      filename: 'maintenance_categories.ttl.bz2'
  wikidata:
    resource_properties:
      filename: 'wikidata_resource_properties.nt.bz2'
      url: ~
  evaluation:
    category_properties:
      filename: 'cataxioms_labels.csv'

results:
  cataxioms:
    category_axioms: 'category-axioms.csv'
    relation_assertions_lcwa_true: 'relation-assertions_lcwa-true.nt'
    relation_assertions_lcwa_false: 'relation-assertions_lcwa-false.nt'

cache:
  # version 2: added resource types from sdtyped + lhd
  # version 3: cataxioms with materialized category graph
  catgraph_conceptual:
    filename: 'catgraph-conceptual'
    version: 1
  catgraph_cyclefree:
    filename: 'catgraph-cyclefree'
    version: 1
  catgraph_dbp_typed:
    filename: 'catgraph-dbp-typed'
    version: 2
  catgraph_taxonomic:
    filename: 'catgraph-taxonomic'
    version: 2
  categories_conceptual:
    filename: 'categories-conceptual'
    version: 1
  categories_singularized:
    filename: 'categories-singularized'
    version: 1
  spacy_docs:
    filename: 'spacy-docs'
    version: 1
  dbpedia_resource_type_cooccurrence_matrix:
    filename: 'dbpedia-resource-type-cooccurrence-matrix'
    version: 2
  dbpedia_resource_type_frequency:
    filename: 'dbpedia-resource-type-frequency'
    version: 2
  dbpedia_resource_type_mapping:
    filename: 'dbpedia-resource-type-mapping'
    version: 2
  dbpedia_resource_labels:
    filename: 'dbpedia-resource-labels'
    version: 1
  dbpedia_resource_surface_forms:
    filename: 'dbpedia-resource-surface-forms'
    version: 1
  dbpedia_resource_surface_scores:
    filename: 'dbpedia-resource-surface-scores'
    version: 1
  dbpedia_resource_categories:
    filename: 'dbpedia-resource-categories'
    version: 1
  dbpedia_resource_properties:
    filename: 'dbpedia-resource-properties'
    version: 1
  dbpedia_inverse_resource_properties:
    filename: 'dbpedia-inverse-resource-properties'
    version: 1
  dbpedia_resource_interlanguage_links:
    filename: 'dbpedia-resource-interlanguage-links'
    version: 1
  dbpedia_resource_redirects:
    filename: 'dbpedia-resource-redirects'
    version: 1
  dbpedia_functional_predicates:
    filename: 'dbpedia-functional-predicates'
    version: 1
  dbpedia_categories:
    filename: 'dbpedia-categories'
    version: 1
  dbpedia_category_resources:
    filename: 'dbpedia-category-resources'
    version: 1
  dbpedia_category_children:
    filename: 'dbpedia-category-children'
    version: 1
  dbpedia_property_frequency_distribution:
    filename: 'dbpedia-property-frequency-distribution'
    version: 1
  dbpedia_list_equivalents:
    filename: 'dbpedia-list-equivalents'
    version: 1
  dbpedia_list_children:
    filename: 'dbpedia-list-children'
    version: 1
  wikidata_dbpedia_resource_mapping:
    filename: 'wikidata-dbpedia-resource-mapping'
    version: 1
  wikidata_resource_properties:
    filename: 'wikidata-resource-properties'
    version: 1
  cataxioms_category_statistics:
    filename: 'cataxioms-category-statistics'
    version: 3
  cataxioms_candidates:
    filename: 'cataxioms-candidates'
    version: 3