# -- SYSTEM CONFIGURATION --
max_cpus: 20

# -- CALIGRAPH CONFIGURATION --
caligraph:
  version: '2.2.0'
  creation_date: '2022-04-05'
  root_node: 'Thing'
dbpedia:
  disjointness_threshold: 0.132  # in the original paper: 0.17
category:
  root_category: 'Category:Main_topic_classifications'
cat2ax:
  pattern_confidence: 0.05
subject_entity:
  model_mention_detection: 'roberta-base'
  negative_sample_size: 0.3
cali2ax:
  pattern_confidence: 0.17
listing:
  valid_tag_threshold: 0.35
  type_mean_threshold: 0.9
  type_std_threshold: 0.2
  relation_mean_threshold: 0.85
  relation_std_threshold: 0.2

# -- LOGGING CONFIGURATION --
logging:
  level: 'DEBUG'
  to_file: False
  filename: 'caligraph_v2_2_0'

# -- ERROR-MAILER CONFIGURATION --
# -> add information about your mail accounts here and enable the `success` or `error` switches
#    if you want to receive information about success or failure of the extraction by mail. <-
mailer:
  sender: ~
  password: ~
  receiver: ~
  subject: ~
  enable:
    success: False
    error: False

# -- SOURCE FILE CONFIGURATION --
files:
  wikipedia:
    pages:
      filename: 'pages_articles_en.xml.bz2'
      url: 'https://dumps.wikimedia.org/enwiki/20201001/enwiki-20201001-pages-articles-multistream.xml.bz2'
  dbpedia:
    taxonomy:
      filename: 'dbpedia_ontology.nt'
      url: 'http://akswnc7.informatik.uni-leipzig.de/dstreitmatter/archivo/dbpedia.org/ontology--DEV/2020.12.02-031001/ontology--DEV_type=parsed.nt'
    labels:
      filename: 'labels_lang=en.ttl.bz2'
      url: 'https://downloads.dbpedia.org/repo/dbpedia/generic/labels/2020.10.01/labels_lang=en.ttl.bz2'
    category_articles:
      filename: 'categories_lang=en_articles.ttl.bz2'
      url: 'https://downloads.dbpedia.org/repo/dbpedia/generic/categories/2020.10.01/categories_lang=en_articles.ttl.bz2'
    category_skos:
      filename: 'categories_lang=en_skos.ttl.bz2'
      url: 'https://downloads.dbpedia.org/repo/dbpedia/generic/categories/2020.10.01/categories_lang=en_skos.ttl.bz2'
    topical_concepts:
      filename: 'topical_concepts_lang=en.ttl.bz2'
      url: 'https://downloads.dbpedia.org/repo/dbpedia/generic/topical-concepts/2020.10.01/topical-concepts_lang=en.ttl.bz2'
    instance_types:
      filename: 'instance-types_lang=en_specific.ttl.bz2'
      url: 'https://downloads.dbpedia.org/repo/dbpedia/mappings/instance-types/2020.10.01/instance-types_lang=en_specific.ttl.bz2'
    mappingbased_literals:
      filename: 'mappingbased-literals_lang=en.ttl.bz2'
      url: 'https://downloads.dbpedia.org/repo/dbpedia/mappings/mappingbased-literals/2020.10.01/mappingbased-literals_lang=en.ttl.bz2'
    mappingbased_objects:
      filename: 'mappingbased-objects_lang=en.ttl.bz2'
      url: 'https://downloads.dbpedia.org/repo/dbpedia/mappings/mappingbased-objects/2020.10.01/mappingbased-objects_lang=en.ttl.bz2'
    anchor_texts:
      filename: 'anchor_text_en.ttl.bz2'
      url: 'https://downloads.dbpedia.org/repo/dbpedia/generic/anchor-text/2020.10.01/anchor-text_lang=en.ttl.bz2'
    redirects:
      filename: 'redirects_lang=en.ttl.bz2'
      url: 'https://downloads.dbpedia.org/repo/dbpedia/generic/redirects/2020.10.01/redirects_lang=en_transitive.ttl.bz2'
    disambiguations:
      filename: 'disambiguations_lang=en.ttl.bz2'
      url: 'https://downloads.dbpedia.org/repo/dbpedia/generic/disambiguations/2020.10.01/disambiguations_lang=en.ttl.bz2'
    page_ids:
      filename: 'page_lang=en_ids.ttl.bz2'
      url: 'https://downloads.dbpedia.org/repo/dbpedia/generic/page/2020.10.01/page_lang=en_ids.ttl.bz2'
    nif_context:
      filename: 'nif-context_lang=en.ttl.bz2'
      url: 'https://downloads.dbpedia.org/repo/dbpedia/text/nif-context/2020.07.01/nif-context_lang=en.ttl.bz2'
    short_abstracts:
      filename: 'short-abstracts_lang=en.ttl.bz2'
      url: 'https://downloads.dbpedia.org/repo/dbpedia/text/short-abstracts/2020.07.01/short-abstracts_lang=en.ttl.bz2'
    wikilinks:
      filename: 'wikilinks_lang=en.ttl.bz2'
      url: 'https://downloads.dbpedia.org/repo/dbpedia/generic/wikilinks/2020.10.01/wikilinks_lang=en.ttl.bz2'
    embedding_vectors:
      filename: 'embeddings_dbpedia2020_rdf2vec.txt.bz2'
      url: 'http://data.dws.informatik.uni-mannheim.de/CaLiGraph/data/embeddings_dbpedia2020_rdf2vec.txt.bz2'
    webisalod_hypernyms:
      filename: 'webisalod_hypernyms.p.bz2'
      url: 'http://data.dws.informatik.uni-mannheim.de/CaLiGraph/data/webisalod_hypernyms.p.bz2'
  listpages:
    goldstandard_named-entity-tagging:
      filename: 'goldstandard_list-page-named-entity-tagging.json'
      url: 'http://data.dws.informatik.uni-mannheim.de/CaLiGraph/data/goldstandard_list-page-named-entity-tagging.json'
    goldstandard_mention-detection:
      filename: 'goldstandard_mention-detection.csv'

# -- RESULT FILE CONFIGURATION --
results:
  caligraph:
    metadata: 'caligraph-metadata.nt.bz2'  # void description
    ontology: 'caligraph-ontology.nt.bz2'  # class hierarchy, labels
    ontology_dbpedia-mapping: 'caligraph-ontology_dbpedia-mapping.nt.bz2'  # equivalent classes and equivalent properties in DBpedia
    ontology_provenance: 'caligraph-ontology_provenance.nt.bz2'  # provenance information for classes
    instances_types: 'caligraph-instances_types.nt.bz2'  # instance types
    instances_transitive-types: 'caligraph-instances_transitive-types.nt.bz2'  # (additional) materialized instance types
    instances_labels: 'caligraph-instances_labels.nt.bz2'  # instance labels
    instances_relations: 'caligraph-instances_relations.nt.bz2'  # all relations
    instances_restriction-relations: 'caligraph-instances_restriction-relations.nt.bz2'  # materialized relations (only from restrictions)
    instances_dbpedia-mapping: 'caligraph-instances_dbpedia-mapping.nt.bz2'  # sameAs links to DBpedia
    instances_provenance: 'caligraph-instances_provenance.nt.bz2'  # provenance information for instances

    dbpedia_instances: 'dbpedia_caligraph-instances.nt.bz2'  # new dbpedia instances found through CaLiGraph
    dbpedia_instance-types: 'dbpedia_caligraph-types.nt.bz2'  # new dbpedia types found through CaLiGraph
    dbpedia_instance-caligraph-types: 'dbpedia_caligraph-clg-types.nt.bz2'  # all CaLiGraph types that can be assigned to DBpedia resources
    dbpedia_instance-transitive-caligraph-types: 'dbpedia_caligraph-transitive-clg-types.nt.bz2'  # all transitive CaLiGraph types that can be assigned to DBpedia resources
    dbpedia_instance-relations: 'dbpedia_caligraph-relations.nt.bz2'  #  new dbpedia relations found through CaLiGraph

    sunburst_type_distribution: 'caligraph_sunburst-type-distribution.json'  # type distribution of CaLiGraph as source for a SolarBurst diagram

# -- CACHE FILE CONFIGURATION --
cache:
  spacy_cache:
    filename: 'spacy-cache'
    version: 2
  wikipedia_raw_markup:
    filename: 'wikipedia-raw-markup'
    version: 2
    compress: True
  wikipedia_parent_categories:
    filename: 'wikipedia-parent-categories'
    version: 2
  wikipedia_parsed_pages:
    filename: 'wikipedia-parsed-pages'
    version: 3
  wikipedia_type_lexicalisations:
    filename: 'wikipedia-type-lexicalisations'
    version: 2
  wikipedia_hypernyms:
    filename: 'wikipedia-hypernyms'
    version: 2
  wikitaxonomy_hypernyms:
    filename: 'wikitaxonomy-hypernyms'
    version: 2
    compress: True
  dbpedia_classes:
    filename: 'dbpedia-classes'
    version: 2
  dbpedia_resources:
    filename: 'dbpedia-resources'
    version: 2
  dbpedia_resource_labels:
    filename: 'dbpedia-resource-labels'
    version: 2
  dbpedia_resource_surface_forms:
    filename: 'dbpedia-resource-surface-forms'
    version: 2
  dbpedia_resource_surface_form_references:
    filename: 'dbpedia-resource-surface-form-references'
    version: 2
  dbpedia_resource_abstracts:
    filename: 'dbpedia-resource-abstracts'
    version: 2
  dbpedia_resource_wikilinks:
    filename: 'dbpedia-resource-wikilinks'
    version: 2
  dbpedia_resource_types:
    filename: 'dbpedia-resource-types'
    version: 2
  dbpedia_resource_typelabels:
    filename: 'dbpedia-resource-typelabels'
    version: 2
  dbpedia_resource_properties:
    filename: 'dbpedia-resource-properties'
    version: 2
  dbpedia_resource_redirects:
    filename: 'dbpedia-resource-redirects'
    version: 2
  dbpedia_resource_embeddings:
    filename: 'dbpedia-resource-embeddings'
    version: RDF2vec
  dbpedia_categories:
    filename: 'dbpedia-categories'
    version: 2
  dbpedia_category_children:
    filename: 'dbpedia-category-children'
    version: 2
  dbpedia_category_labels:
    filename: 'dbpedia-category-labels'
    version: 2
  dbpedia_category_resources:
    filename: 'dbpedia-category-resources'
    version: 2
  dbpedia_category_sets:
    filename: 'dbpedia-category-sets'
    version: 2
  dbpedia_heuristic_domains:
    filename: 'dbpedia-heuristic-domains'
    version: 2
  dbpedia_heuristic_ranges:
    filename: 'dbpedia-heuristic-ranges'
    version: 2
  dbpedia_heuristic_disjoint_types:
    filename: 'dbpedia-heuristic-disjoint-types'
    version: 2
  dbpedia_list_equivalents:
    filename: 'dbpedia-list-equivalents'
    version: 2
  dbpedia_list_parents:
    filename: 'dbpedia-list-parents'
    version: 2
  cat2ax_axioms:
    filename: 'cat2ax-axioms'
    version: 2
  catgraph_conceptual:
    filename: 'catgraph-conceptual'
    version: 2
  catgraph_wikitaxonomy:
    filename: 'catgraph-wikitaxonomy'
    version: 2
  catgraph_merged:
    filename: 'catgraph-merged'
    version: 2
  listgraph_base:
    filename: 'listgraph-base'
    version: 2
  listgraph_wikitaxonomy:
    filename: 'listgraph-wikitaxonomy'
    version: 2
  listgraph_merged:
    filename: 'listgraph-merged'
    version: 2
  spacy_listpage_ne-tagging:
    filename: 'spacy_listpage_ne-tagging'
    version: 2
    store_as_folder: True
  subject_entity_listpage_labels:
    filename: 'subject-entity-listpage-labels'
    version: 4
  subject_entity_mentions_noisy:
    filename: 'subject-entity-mentions-noisy'
    version: 4
  subject_entity_mentions:
    filename: 'subject-entity-mentions'
    version: 4
  transformer_for_listpage_mention_detection:
    filename: 'transformer-for-listpage-mention-detection'
    version: 4
    store_as_folder: True
  transformer_for_page_mention_detection:
    filename: 'transformer-for-page-mention-detection'
    version: 4
    store_as_folder: True
  caligraph_ontology:
    filename: 'caligraph-ontology'
    version: 2
  caligraph_entities:
    filename: 'caligraph-entities'
    version: 2
  cali2ax_axioms:
    filename: 'cali2ax-axioms'
    version: 3
  listing_page_entities:
    filename: 'listing-page-entities'
    version: 3

# WIP
  word_blocker_exact:
    filename: 'word-blocker-exact'
    version: RDF2vec
  MD_listpage_data:
    filename: 'MD-listpage-data'
    version: 5
  MD_listpage_train:
    filename: 'MD-listpage-train'
    version: 5
  MD_listpage_eval:
    filename: 'MD-listpage-eval'
    version: 5
  MD_page_train:
    filename: 'MD-page-train'
    version: 5
  MD_page_test:
    filename: 'MD-page-test'
    version: 5
  ED_datasets:
    filename: 'ED-datasets'
    version: 1