approach: nl
corpus: NILK
sample_size: 10
# params
mm_approach: [NILK10v2Fcr937]
me_approach: [NILK10v1Fbi820, NILK10v2Fcr937]
mm_threshold: [0.75, 0.8, 0.85, 0.9, 0.95]
me_threshold: [0.75, 0.8, 0.85, 0.9, 0.95]
path_threshold: [0.75, 0.8, 0.85]