approach: nl
corpus: NILK
sample_size: 50
# params
mm_approach: [NILK50v1Fbi941]
me_approach: [NILK50v1Fbi941, NILK50v1MEcr089]
mm_threshold: [0.75, 0.8, 0.85, 0.9, 0.95]
me_threshold: [0.75, 0.8, 0.85, 0.9, 0.95]
path_threshold: [0.75, 0.8, 0.85]